CREATE OR REPLACE PACKAGE CUSTOMER_MANAGER AS
    FUNCTION GET_TOTAL_PURCHASE(customer_id IN NUMBER) RETURN NUMBER;
    FUNCTION CHOOSE_GIFT_PACKAGE(p_total_purchase IN NUMBER) RETURN NUMBER;
    PROCEDURE ASSIGN_GIFTS_TO_ALL;
END CUSTOMER_MANAGER;
/