CREATE TABLE CUSTOMER_REWARDS (
    REWARD_ID NUMBER PRIMARY KEY,
    CUSTOMER_EMAIL VARCHAR2(255 CHAR),
    GIFT_ID NUMBER,
    REWARD_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (GIFT_ID) REFERENCING GIFT_CATALOG(GIFT_ID) 
);